# Generated by Django 3.0.6 on 2020-06-10 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id_fun', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fun', models.CharField(max_length=200)),
                ('horas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id_tar', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tar', models.CharField(max_length=200)),
                ('fk_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridges_app.Projetos')),
            ],
        ),
    ]
