# Generated by Django 3.0.6 on 2020-06-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0002_auto_20200610_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='horas_limite',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dur_tar',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
