# Generated by Django 3.0.6 on 2020-06-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0003_auto_20200610_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='dur_tar_min',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
            preserve_default=False,
        ),
    ]
