# Generated by Django 3.0.6 on 2020-06-21 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0004_tarefas_dur_tar_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('fk_fun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridges_app.Funcionarios')),
                ('fk_tar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridges_app.Tarefas')),
            ],
        ),
        migrations.RemoveField(
            model_name='Tarefas',
            name='dur_tar',
        ),
        migrations.AddField(
            model_name='Tarefas',
            name='dur_tar_horas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
