# Generated by Django 3.0.6 on 2020-06-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0005_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='dur_tar_horas',
            new_name='dur_tar_hours',
        ),
    ]
