# Generated by Django 3.0.6 on 2020-06-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0007_auto_20200626_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='dias_semana',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
