# Generated by Django 3.0.6 on 2020-06-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0008_funcionarios_dias_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='horas_limite',
            field=models.TimeField(),
        ),
    ]
