# Generated by Django 3.0.6 on 2020-06-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0009_auto_20200626_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='dt_fim',
        ),
    ]
