# Generated by Django 3.0.6 on 2020-06-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges_app', '0010_remove_agenda_dt_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='dt_fim',
            field=models.DateField(default='2020-06-24'),
            preserve_default=False,
        ),
    ]
